-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIPIu8HvxBQclY+L7zanOlDlEtMBoTr73an3um/Mi9uxMoAoGCCqGSM49
AwEHoUQDQgAExF4V/Kmt3mFh8GQNX5kc8IHUjYGb/pMDtU/OFAq1g/XG4Kv/8Hzz
Hbs8S2EjoxGu+dd2M3uDAXiowMpBTRQU2A==
-----END EC PRIVATE KEY-----
