-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIKySsV1qIETa/TFHniGyYsBYgCC2VbFr2QOsNPKo4HNDoAoGCCqGSM49
AwEHoUQDQgAEkVPJ240ky+vHEte5GGYBCig2JjtfOevGjrL0dlo3WaGCm0nC/i8k
Psk+2aS65REmXzb9pQ1fXqELIFgvHRssXA==
-----END EC PRIVATE KEY-----
